# Generated by Django 4.2.9 on 2024-08-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_expense_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
